package com.projetimmo.projet_immobilier.enums;

public enum TypeDocumentBien {
    TITRE_PROPRIETE,
    TITRE_FONCIER,
    PLAN_CADASTRAL,
    PLAN_ARCHITECTURE,
    CERTIFICAT_CONFORMITE,
    DIAGNOSTIC_ENERGETIQUE,
    PERMIS_CONSTRUIRE,
    CARRE_TERRE,
    FACTURES_EAU,
    FACTURES_ELECTRICITE,
    FACTURES_GAZ,
    TAXE_FONCIERE,
    TAXE_HABITATION,
    REGLEMENT_COPROPRIETE,
    PROCES_VERBAL_ASSEMBLEE,
    ETAT_LIEUX,
    PHOTOS_BIEN,
    VIDEO_BIEN,
    AUTRE
}
