package com.projetimmo.projet_immobilier.enums;

public enum TypeDocumentAgence {
    // Ancien libellé conservé pour compatibilité (legacy)
    LICENCE_PROFESSIONNELLE,
    // Nouveau libellé officiel
    AGREMENT,
    NIF,
    CARTE_PROFESSIONNELLE,
    REGISTRE_COMMERCE,
    AUTORISATION_AGENCE,
    STATUTS_JURIDIQUES,
    ATTESTATION_ASSURANCE,
    ATTESTATION_FISCALE,
    PIECE_IDENTITE_RESPONSABLE,
    PIECES_IDENTITE_DIRIGEANT,
    JUSTIFICATIF_DOMICILE,
    RIB,
    CONTRAT_BAIL_LOCAL,
    AUTORISATION_PREFECTORALE,
    CERTIFICAT_NON_SITUATION,
    DECLARATION_ACTIVITE,
    FORMATION_PROFESSIONNELLE,
    AUTRE
}
